#ifndef _ADT7516_R_H_
#define _ADT7516_R_H_

#include "stm32f10x.h"

// Регистры
typedef enum {
	INTERRUPT_STATUS1 = 0x00,
	INTERRUPT_STATUS2,
	INT_TMP_VDD_L = 0x03,
	EXT_TMP_AIN14_L,
	INT_VDD_M = 0x06,
	INT_TMP_M,
	EXT_TMP_AIN1_M,
	AIN2_M,
	AIN3_M,
	AIN4_M,
	DAC_A_L = 0x10,
	DAC_A_M,
	DAC_B_L,
	DAC_B_M,
	DAC_C_L,
	DAC_C_M,
	DAC_D_L,
	DAC_D_M,
	CNTRL_CONF1,
	CNTRL_CONF2,
	CNTRL_CONF3,
	DAC_CONF,
	LDAC_CONF,
	INTERRUPT_MASK1,
	INTERRUPT_MASK2,
	INT_TMP_OFFSET,
	EXT_TMP_OFFSET,
	INT_ATMP_OFFSET,
	EXT_ATMP_OFFSET,
	VDD_VHIGH_LIM,
	VDD_VLOW_LIM,
	INT_THIGH_LIM,
	INT_TLOW_LIM,
	EXT_THIGH_AIN1_VHIGH_LIM,
	EXT_TLOW_AIN1_VLOW_LIM,
	AIN2_VHIGH_LIM = 0x2B,
	AIN2_VLOW_LIM,
	AIN3_VHIGH_LIM,
	AIN3_VLOW_LIM,
	AIN4_VHIGH_LIM,
	AIN4_VLOW_LIM,
	DEVICE_ID = 0x4D,
	MANUFACTURES_ID,
	SILICON_REV,
	SPI_LOCK_STATUS = 0x7F
} ADT7516_RegistersADDR;

#endif // _ADT7516_R_H_
